---
#    _    _   _       _                                   _      _____                 _    
#   | |  | | (_)     | |              /\                 | |    / ____|               | |   
#   | |__| |  _    __| |   ___       /  \     _ __     __| |   | (___     ___    ___  | | __
#   |  __  | | |  / _` |  / _ \     / /\ \   | '_ \   / _` |    \___ \   / _ \  / _ \ | |/ /
#   | |  | | | | | (_| | |  __/    / ____ \  | | | | | (_| |    ____) | |  __/ |  __/ |   < 
#   |_|  |_| |_|  \__,_|  \___|   /_/    \_\ |_| |_|  \__,_|   |_____/   \___|  \___| |_|\_\
#                                                                                           
#                                                                                           
# The original minigame, free, and better than ever !
# @author SkulZOnTheYT
# youtube SkulZ
name: HideAndSeek
author:  SkulZOnTheYT
version: 1.0
api: [4.0.0]
main: SkulZTeams\HideAndSeek\Main
load: POSTWORLD
commands:
  hideandseek:
    description: Main HideAndSeek management command
    usage: /hideandseek <sub command> [parameters]
    permission: hideandseek.cmd
    aliases: [hide&seek, h&s]
permissions: 
  hideandseek.cmd:
    default: true
    description: /hideandseek permission
...
